// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	pgxpool "github.com/jackc/pgx/v5/pgxpool"
)

// Mockdbpool is an autogenerated mock type for the dbpool type
type Mockdbpool struct {
	mock.Mock
}

type Mockdbpool_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockdbpool) EXPECT() *Mockdbpool_Expecter {
	return &Mockdbpool_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx
func (_m *Mockdbpool) Acquire(ctx context.Context) (*pgxpool.Conn, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 *pgxpool.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*pgxpool.Conn, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *pgxpool.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockdbpool_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type Mockdbpool_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Mockdbpool_Expecter) Acquire(ctx interface{}) *Mockdbpool_Acquire_Call {
	return &Mockdbpool_Acquire_Call{Call: _e.mock.On("Acquire", ctx)}
}

func (_c *Mockdbpool_Acquire_Call) Run(run func(ctx context.Context)) *Mockdbpool_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Mockdbpool_Acquire_Call) Return(_a0 *pgxpool.Conn, _a1 error) *Mockdbpool_Acquire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockdbpool_Acquire_Call) RunAndReturn(run func(context.Context) (*pgxpool.Conn, error)) *Mockdbpool_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function with given fields: ctx
func (_m *Mockdbpool) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockdbpool_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type Mockdbpool_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Mockdbpool_Expecter) Begin(ctx interface{}) *Mockdbpool_Begin_Call {
	return &Mockdbpool_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *Mockdbpool_Begin_Call) Run(run func(ctx context.Context)) *Mockdbpool_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Mockdbpool_Begin_Call) Return(_a0 pgx.Tx, _a1 error) *Mockdbpool_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockdbpool_Begin_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *Mockdbpool_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdbpool creates a new instance of Mockdbpool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdbpool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockdbpool {
	mock := &Mockdbpool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
